### ISSUE TITLE
Fix the button design of landing page

### ISSUE THREAD

**Issue by Biboswan** [UdacityMobileWebScholarship/udabot#18]
Right now the button doesn't have any styling.
Design should be identical to that in https://github.com/UdacityMobileWebScholarship/udabot/blob/master/Guidelines/Screen1.jpg

This is the file where you need to look at for fixing this issue: https://github.com/UdacityMobileWebScholarship/udabot/tree/frontend/Frontend/udabot/src/componenets/CustomButton

**Comment by blenderskool** [comment]
I am working on this :slightly_smiling_face:
