### ISSUE TITLE
Wiki link doesn't have setup instructions

### ISSUE THREAD

**Issue by PN1019** [UdacityMobileWebScholarship/udabot#7]
I was going through the README.md  as mentioned there it has set up instructions in the wiki so I think this should fix asap so that contributors can start figuring out how the code is working, contributors must know how to setup code, etc??

**Comment by anshumanv** [comment]
Good find @PN1019, are you willing to fix it?

**Comment by PN1019** [comment]
@anshumanv sure I can do this will need your help in figuring out how the setup works?

**Comment by anshumanv** [comment]
The setup will be added to the wiki by the maintainers, please just correct the link to it.

**Comment by PN1019** [comment]
@anshumanv well this is fixed now by @Biboswan ...!!! so closing this issue!!
